IcedFrisby/IcedFrisby

.travis.yml
CHANGELOG.md
README.md
lib/icedfrisby.js
package.json
spec/frisby_output_spec.js

Upgraded all of the dependencies on the project to latest stable with the exception of lodash. Lodash was upgraded to the latest stable 3.x branch (4.x being the latest). All 245 tests passed.

futureproof icedfrisby

---

test/frisby_httpbin.js

This commit compensates for new httpbin header details.

fix httpbin tests - update joi header objects

---

README.md

Tidy up badges

---

test/frisby_mock_request.js

This adds tests for `delete`, `head`, `options`, and `afterJSON`, and covers some code paths that were previously not covered in `expectHeaderToMatch` and the JSON request code.

Fill in some test coverage

---

.eslintrc.yml
lib/icedfrisby.js
lib/pathMatch.js

A good post on the subject:
https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

Use block scoping in lib/, const where possible

---

API.md
lib/icedfrisby.js
test/frisby_mock_request.js

Hi there,
in reference to issue #57, here's a PR showing that async hooks are possible.
Let me know what you think, e.g. if it's better to explicitly check for timeouts within frisby etc.

Async hooks for before(), after(), finally()

---

README.md

It's cool to see that someone else has written a plugin!

Add a plugin to the readme

---

API.md
test/frisby_mock_request.js

Added docs and tests for the max response time assertion.

Complete expectMaxResponseTime

---

package-lock.json

#82 did not account for #72 which was in flight at the same time.

Update lockfile for previous

---

lib/icedfrisby.js

remove setResponseX functions

---

API.md

Around half of the day-to-day functions I use were missing from the API docs. I've had a first crack at backfilling.

Better API docs

---

CHANGELOG.md
LICENSE.md
README.md
package.json

I'd like to start using some of the features we've been working on!
I feel like we can keep developing toward 2.0, and issue alphas periodically. How does that sound?

RELEASE 2.0.0-alpha1

---

lib/icedfrisby.js
test/frisby_global.js
test/frisby_httpbin.js
test/frisby_mock_request.js

This has a puzzling test failures which I haven't understood yet.

More renames, emptying out this.current

---

API.md
README.md
lib/icedfrisby.js
test/frisby_httpbin.js
test/frisby_mock_request.js
test/frisby_output.js

This is a work in progress; see discussion in #104.

Remove globalSetup() and reset(), add config()

---

package-lock.json
package.json

I've started working on nock, and it'd be great to exercise some of the new work here.

Update to nock beta

---

.circleci/config.yml
README.md
package.json

Discussed with @Fishbowler offline.

Drop support for Node 6

---

.circleci/config.yml
.eslintrc.yml
.prettierignore
.prettierrc.yml
CONTRIBUTING.md
package-lock.json
package.json

Prettier provides a pretty fabulous format-on-save experience that is way better than eslint. It also generates really pretty code, formats code inside of Markdown, and formats config files.
They work well together: ESLint for semantic issues and Prettier for formatting.

Set up Prettier

---

.eslintrc.yml
lib/icedfrisby.js

This seems like the cleanest first step toward #179.

Refactor _runHooks to return a promise

---

.prettierignore
package-lock.json
package.json

Hopefully will fix this instrumentation error: https://circleci.com/gh/IcedFrisby/IcedFrisby/103

Swap Istanbul for NYC

---

API.md
lib/icedfrisby.js
package-lock.json
package.json
test/frisby_mock_request.js

Add async run() method

---

lib/icedfrisby.js

This groups like with like a bit more, and aims to list methods before the methods that call them.

Reorder methods

---

lib/pathMatch.js
package-lock.json
package.json
test/frisby_httpbin.js
test/frisby_mock_request.js
test/pathMatch.js

Ref badges/shields#3505
> [Joi](https://www.npmjs.com/package/joi) is dead
> long live [Joi](https://www.npmjs.com/package/@hapi/joi)

BREAKING CHANGE: Switch .checkJSONTypes() from joi to @hapi/joi

---

CHANGELOG.md
README.md
package.json

Thought I would prepare for the 2.0.0 release. I feel like the docs are in pretty good shape. I wrote a combined changelog and and added an upgrade guide to the readme.

RELEASE 2.0.0

---

API.md
lib/icedfrisby.js
test/frisby_mock_request.js

Add `skip()` and `skipIf()`

---

package-lock.json
package.json
test/frisby_output.js

test: Avoid hard-coding ANSI sequences
