IcedFrisby/IcedFrisby

lib/icedfrisby.js

I was unsatisfied with Mocha's default output for failures when used with frisby--
When a test fails it spits out a stack trace, which is less than useful when you're debugging an HTTP request.
This change attaches the request and response to the test so that they may be referenced from a custom mocha reporter. I may release the reporter as well, if this is merged. It basically just displays the exact request made (in the form of a curl command) and the raw response that was returned. This helps to quickly fix issues when they occur.

Add contextual information to be used in mocha reporters

---

API.md
README.md
lib/icedfrisby.js
spec/frisby_inspect.spec.js

This also includes tests and API docs.

Fixes issue #6 where inspect*() does not work if the test does not pass.

---

lib/icedfrisby.js

This fixes the unchecked overwriting of an already 
defined `Content-Type` header field set via `#addHeader()`
when sending a `PUT` request with `{ json: true }`
Sample: 
```javascript
frisby
.create()
.setHeader('content-type', 'application/json;charset=utf-8')
.put('http://endpoint/', {}, { json:true }
.inspectRequest()
.toss()
```
Output from ```#inspectRequest()```
Before: 
```json
'content-type': 'application/json'
```
After:
```json
'content-type': 'application/json;charset=UTF-8'
```

refactor(lib): add check for content-type header

---

lib/icedfrisby.js

When useApp is used in the global setup, don't spin up the app for every test

When useApp is used in the global setup, don't spin up the app for every test

---

package.json
spec/frisby_output_spec.js

Fixes #18 
I wasn't a 100% certain what BSD clause license you wanted to use so I opted for the basic 3 clause license which I believe is the most popular/standard. It's too bad package.json doesn't support dual licensing because I also noticed the MIT licensing too.

updates to package.json and unittests

---

lib/icedfrisby.js
test/frisby_mock_request.js

Thanks for this library! I'm working on some tests for [shields](https://github.com/badges/shields) (see badges/shields#927). This library seems well suited for the purpose: the tests come out really concise, it has good test coverage itself, y'all seem reponsive to PRs, and it uses Mocha and Chai.
I noticed this in the readme:
> Make output errors more useful. It can be hard to track down which assertion is causing what error.
Shields has a years-long backlog. The goal of these tests is to distribute the work of reviewing and testing to a wide net of contributors. Many of the contributors are unfamiliar with Node and JavaScript, so concise and readable tests are important, but so are good error messages.
I've started work on a POC, and I'll see what my experience with the error messaging …

baseUri function to override global setup

---

README.md
package.json

- Add mocha as a peerDependency
- Bump devDependencies
- Remove one unused devDependency
- Correctly classify mock-request as a devDependency
- Readme updates
- Downstream users will need to install mocha.
- There's no need to manually install jshint.

Dependencies housekeeping

---

.eslintignore
.eslintrc.yml
.jshintrc
lib/icedfrisby.js
lib/pathMatch.js
package.json
test/frisby_global.js
test/frisby_httpbin.js
test/frisby_inspect.js
test/frisby_mock_request.js
test/frisby_output.js
test/frisby_useApp.js
test/pathMatch.js

This switches the linter from JSHint to ESLint. ESLint is a superior tool for a number of reasons:
- Has a large and highly engaged core team with awesome community culture
- Has a vast community, which means tons of plugins
- There's one for Mocha, which I've included
- Great error messages
- Autofix, where many errors can be fixed automatically with the `--fix` flag
- The "recommended" rules catch a bunch of things which JSHint did not
- It's great at enforcing style conventions as well as common errors. Before ESLint, you had to use a combination of JSHint and JSCS. (JSCS has now merged with ESLint.)
- It's style agnostic, which means we can find a style preset we like, or pick our own rules
- Rules are carefully implemented and tested. False positives are extremely rare, once config …

Switch from jshint to eslint, and clean

---

lib/icedfrisby.js

- Sequence test methods in order of invocation
- Clarify in comments that toss() registers the tests. They are not run
immediately.
- toss() does not return a value

Extract a _start() method from toss() to aid readability

---

lib/icedfrisby.js

- Apply and enforce consistent indentation
- Switch a couple JSDoc comments to consistent format
- Consistent spacing between methods

Update Frisby to an ES6 class

---

.eslintrc.yml
lib/icedfrisby.js
lib/pathMatch.js
test/app_integration_express/expressApp.js
test/expressApp.js
test/frisby_global.js
test/frisby_httpbin.js
test/frisby_inspect.js
test/frisby_mock_request.js
test/frisby_output.js
test/frisby_useApp.js
test/pathMatch.js

This cleans up all the indentation across the project, which was a mix of 2 and 4 spaces, and removes semicolons. Since the previous commit touched every line in icedfrisby.js, and both of these touch every line, it makes sense to do now, since "git blame" is already useless
Closes #47.

Enforce indent and remove semicolons

---

lib/icedfrisby.js

This avoids the need for mixin classes to override create().
Related to plugin support (#27).

When composed with mixins, create() should do the right thing

---

lib/icedfrisby.js
test/frisby_mock_request.js

There's a `not()` method, but that one should be removed (or replaced?) IMHO, it only works for some expectations and doesn't reset itself.
This PR adds an `expectNoHeader()` method, complementary to `expectHeader()`.

add expectNoHeader() helper

---

API.md
lib/icedfrisby.js
package.json
test/frisby_mock_request.js

As I use IcedFrisby in growing suites in Shields, I find this increasingly helpful.

Add only() to support exclusive tests

---

API.md

Added `expectNoHeader` and `expectHeaderToMatch` into API.md - were available in the library but not documented

Document missing functions

---

.travis.yml

Since Node 8 was released, we should test on that, and I'd suggest, drop support for Node 7 which was pre-release.

Drop support for Node 7

---

lib/icedfrisby.js
lib/pathMatch.js

- Use arrow functions where they improve clarity
- Don’t use lodash where vanilla ES6 works fine

Update for ES6

---

.travis.yml
package-lock.json

There's a fair amount of FUD out there about whether lock files are beneficial for libraries. It's difficult to sift through it all. I read [this post on the yarn blog](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) which convinced me to give it a try. Greenkeeper supports lock files and has [a tool for updating them](https://blog.greenkeeper.io/greenkeeper-support-for-lockfiles-9d9c282efcbe).
The alternative would be to [disable the lock file](https://codeburst.io/disabling-package-lock-json-6be662f5b97d), and not check it in.
We should definitely get out of the current purgatory of local lock files dirtying the working copy.

Use the npm lock file

---

README.md
lib/pathMatch.js
package-lock.json
package.json
test/frisby_mock_request.js

- Joi is only used when the developer invokes `expectJSONTypes`
- The developer must install Joi on their own.
- The developer can specify the version number of their choice. Upgrading IcedFrisby does not affect the Joi version. Joi 12.0.0 works with Node 6+, 13.0.0 with Node 8+.
- The developer's specified version is the only copy of Joi installed.
Close #52

Make Joi an optional dependency

---

lib/icedfrisby.js

This isn't perfect, but it unravels one step of indirection in the request-making process by eliminating the `current.it` closure.

Simplify _request, eliminating state in closure

---

lib/icedfrisby.js
test/frisby_global.js
test/frisby_mock_request.js

Just beginning some more code cleanup. I’d like to get rid of `self.current`, which tends to make the code harder to read and type. I started renaming keys to move them out.
This will be easier to review one commit at a time. When I merge it I'll rebase to keep that history.

Renames for readability

---

lib/icedfrisby.js

This makes it a bit easier to ensure it's being used correctly.

Refactor _runHooks to enqueue its own failures

---

lib/icedfrisby.js

This removes a layer of indirection within `_makeRequest`. This reads much more directly than it did before, though it's a gnarly diff, and the method is still pretty long.

Refactor _makeRequest

---

lib/icedfrisby.js
test/frisby_mock_request.js

Correctly emit exceptions from after() and finally()

---

README.md

expectJSONTypes is specified twice in the README example

Update README.md - dedupe function in example

---

lib/pathMatch.js
package-lock.json
package.json
test/pathMatch.js

Refs #304
Joi 16 moves `validate()` to a method on `schema` and removes the the ability to pass a callback to `validate()` I've switched to using `Joi.assert()` with `try`/`catch` here to minimise disruption.

update for Joi 16

---

README.md

- Repair Markdown structure by adding the missing `]` character to line `29`

docs(readme): repair Markdown structure
